import Vue from 'vue';
import { Lazyload,Tabbar,TabbarItem,Button,Swipe,SwipeItem,Image as VanImage,
    Field,NavBar,Radio,RadioGroup,Checkbox,Toast,Dialog,
    NoticeBar,
    Tab,Tabs,
    List,
    Cell,
    CellGroup,
    PullRefresh,
    Icon,
    Col,Row,
    GoodsAction,
    GoodsActionButton,
    GoodsActionIcon,
    Sku,
    Popup,
    Stepper,
    Tag,
    CountDown,
    SubmitBar
} from 'vant';
Vue.use(Lazyload);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Button);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(VanImage);
Vue.use(Field);
Vue.use(NavBar);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Checkbox);
Vue.use(Toast);
Vue.use(Dialog);
Vue.use(NoticeBar);
Vue.use(Col);
Vue.use(Row);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(List);
Vue.use(PullRefresh);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Icon);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Sku);
Vue.use(Popup);
Vue.use(Stepper);
Vue.use(Tag);
Vue.use(CountDown);
Vue.use(SubmitBar);

